model:
  pretrained: true
  num_ftrs: 1
  loss: 'focal' # 'bce'

training:
  lr: 0.001
  momentum: 0.9
  weight_decay: 1e-4
  num_epochs: 5
  

output_path: "trained_models/model.pth"

dataset:
  data_path: 'C:/Users/risha/Desktop/VU_project/data/dataset/'
  label_file: 'labels.csv'

